### ISSUE TITLE
Ok to add our ocr.space free OCR API?

### ISSUE THREAD

**Issue by A9T9** [toddmotto/public-apis#400]
Hi,

Just found out about this list on HN ;) You write

> This API list is not a marketing tool, but a tool to help the community build applications and use free, public APIs quickly and easily. Pull requests that are identified as marketing attempts will not be accepted.

Now... my [OCR API](https://ocr.space/ocrapi) as a generous free tier of 25,000 conversions/month and many use the API without ever paying a cent. But there are also some "PRO" options... so I am not sure if this fits your list. If it does, let me know, and I create a pull request. 

Mathias

**Comment by davemachado** [comment]
Hi @A9T9 , thanks for reaching out! Always glad to see this project getting some love on HackerNews :)

This project is designed to support free and free-tier services. The idea is a user can click on any service in the project and know that they don't have to spend money to use the service. Now they may be able to spend money to get more calls, but they always have to option to not spend money. We do not support free trial services, such as 30 or 90 day free trials of a paid service, since that does not support the spirit of the project.

That being said, I'm looking forward to reviewing your pull request soon :)
