### ISSUE TITLE
Changing the ReadMe UI

### ISSUE THREAD

**Issue by navanchauhan** [toddmotto/public-apis#543]
I propose changing the readme UI to something like this : [Bash-Snippets](https://github.com/alexanderepstein/Bash-Snippets)

If enough all of you agree, I'll open a pull request

**Comment by mikestreety** [comment]
With the drop downs? Interesting! Certainly neater - although it takes away the "browsability" of the document

**Comment by jbrooksuk** [comment]
I don't think it'll really work very well for the format we have.

**Comment by karllhughes** [comment]
I don't like that you can't `ctrl + f` search it. Other than that it's okay. Not a huge improvement though.

**Comment by davemachado** [comment]
We currently use section headers to jump right to that section in the README, which accomplishes exactly what these dropdowns do, IMO. Plus, since we don't hide anything, we can still search for specific entries.

I started working on the website version of this project this week, so I will have something to show soon 😄

**Comment by mikestreety** [comment]
Thanks for the suggestion though @navanchauhan :)
